env:
  node: true
  commonjs: true
  es2020: true
extends:
  - eslint:recommended
  - plugin:jest/recommended
rules:
  comma-dangle: error
  indent: [error, 4]
  max-len: [error, 120, { ignoreStrings: true, ignoreTemplateLiterals: true }]
  no-multi-spaces: [error, { ignoreEOLComments: true }]
  no-multiple-empty-lines: error
  no-shadow: error
  object-curly-spacing: [error, always]
  quotes: [error, single, { avoidEscape: true }]
  semi: error
  strict: error
