name: Test and Deploy

on:
  pull_request:
  push:
    branches:
      - main

env:
  FORCE_COLOR: 1
  TERM: xterm-color

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install packages
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-20.04
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install packages
        run: npm install --prod

      - name: Deploy to AWS
        run: npm run deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
