name: Test and Deploy

on:
  pull_request:
  push:
    branches:
      - main

env:
  FORCE_COLOR: 1
  TERM: xterm-color

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup cfn-lint
        run: pip3 install --upgrade cfn-lint

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      # - name: Login NPM
      #   run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}

      - name: Install packages
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Run tests
        run: npm test

      - name: Report test coverage
        # Actions run by dependabot are not allowed to update PRs
        if: github.ref != 'refs/heads/main' && github.actor != 'dependabot[bot]'
        uses: artiomtr/jest-coverage-report-action@v2.0-rc.6
        with:
          annotations: none
          github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-22.04
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup cfn-lint
        run: pip3 install --upgrade cfn-lint

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      # - name: Login NPM
      #   run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}

      - name: Install packages
        run: npm install --prod

      - name: Deploy to AWS
        run: npm run deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
